GRAPH_SCHEMA = """
Các node và relationship trong graphDB:
1. Company -[CompanyPublishesJD]-> JD
2. Company -[CompanySpecifiesLocations]-> Locations
3. JD -[JDBelongsToCompany]-> Company
4. JD -[JDBelongsToJobTitle]-> JobTitle
5. JD -[JDRequiresSkills]-> Skills
6. JD -[JDProvidesBenefits]-> Benefits
7. JD -[JDRequiresDegrees]-> Degrees
8. JD -[JDDescribesTasks]-> Tasks
9. JobTitle -[JobTitleDescribesJD]-> JD
10. Skills -[SkillsBelongToJD]-> JD
11. Skills -[CONTAINS]-> Skill
12. Skill -[BELONGS_TO]-> Skills
13. Benefits -[BenefitsBelongToJD]-> JD
14. Benefits -[CONTAINS]-> Benefit
15. Benefit -[BELONGS_TO]-> Benefits
16. Degrees -[DegreesBelongToJD]-> JD
17. Degrees -[CONTAINS]-> Degree
18. Degree -[BELONGS_TO]-> Degrees
19. Locations -[CONTAINS]-> Location
20. Locations -[LocationsBelongToCompany]-> Company
21. Location -[BELONGS_TO]-> Locations
22. Tasks -[TasksBelongToJD]-> JD
23. Tasks -[CONTAINS]-> Task
24. Task -[BELONGS_TO]-> Tasks
25. Candidate -[CandidateHasExperiences]-> Experiences
26. Candidate -[CandidateHasEducations]-> Educations
27. Candidate -[CandidateHasSkills]-> Skills
28. Candidate -[CandidateHasCertificates]-> Certificates
29. Candidate -[CandidateHasLanguages]-> Languages
30. Candidate -[CandidateHasProjects]-> Projects
31. Experiences -[ExperiencesBelongToCandidate]-> Candidate
32. Educations -[CONTAINS]-> Education
33. Educations -[EducationsBelongToCandidate]-> Candidate
34. Education -[BELONGS_TO]-> Educations
35. Skills -[SkillsBelongToCandidate]-> Candidate
36. Certificates -[CONTAINS]-> Certificate
37. Certificates -[CertificatesBelongToCandidate]-> Candidate
38. Certificate -[BELONGS_TO]-> Certificates
39. Languages -[CONTAINS]-> Language
40. Languages -[LanguagesBelongToCandidate]-> Candidate
41. Language -[BELONGS_TO]-> Languages
42. Projects -[CONTAINS]-> Project
43. Projects -[ProjectsBelongToCandidate]-> Candidate
44. Project -[BELONGS_TO]-> Projects
45. Experiences -[CONTAINS]-> Experience
46. Experience -[BELONGS_TO]-> Experiences
"""